title: f0rw4rd
description: ICS Booper | Head of Vulnerability Research @ Limes Security
author: Felix Eberstaller
tagline: Professional OT Pentester & Security Researcher
avatar: /assets/img/avatar.jpg

# Theme
theme: jekyll-theme-chirpy

# Contact
social:
  github: f0rw4rd
  linkedin: felix-eberstaller-3a20251b6

# Navigation
tabs:
  - title: Home
    url: /
  - title: CVEs
    url: /cves/
  - title: Tools & Projects
    url: /tools/

# Build settings
markdown: kramdown
highlighter: rouge
paginate: 10

# Theme mode
theme_mode: dark  # Forces dark theme as default

# SEO
google_analytics: # Add your GA ID
